# Generated by Django 4.1.3 on 2022-11-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='assets/img/default.jpg', null=True, upload_to='avatares'),
        ),
    ]
